version: '3.8'

services:
  # База данных PostgreSQL (основная база)
  postgres:
    image: postgres:15-alpine
    container_name: go-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Исправил имя тома
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # База данных Redis (кеш-база)
  redis:
    image: redis:7-alpine
    container_name: go-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/dat

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    ports:
      - "9092:9092"
      - "8081:8081"
    command: >
      redpanda start
      --overprovisioned
      --node-id 0
      --smp 1
      --reserve-memory 0M
      --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    healthcheck:
      test: [ "CMD", "rpk", "cluster", "info" ]
      interval: 5s
      timeout: 10s
      retries: 5

# Объявляем томы на верхнем уровне
volumes:
  postgres_data:
  redis_data:
