syntax = "proto3";

// Указываем пакет для Go-кода
// последняя часть (pb) — это имя директории, куда сгенерируются файлы
option go_package = "do-learn/api/grpc/pb;pb";

package product;

// Сервис с методом для получения товара
service ProductService {
  rpc GetProduct (GetProductRequest) returns (ProductResponse);
}

// Запрос: нужен только ID
message GetProductRequest {
  int32 product_id = 1;
}

// Ответ: все поля товара
message ProductResponse {
  int32 id = 1;
  string name = 2;
  int32 price = 3;
}