syntax = "proto3";

option go_package = "go-learn/api/grpc/pb";

package product;

// Запрос ORDER->CORE: нужен только ID товара
message GetProductRequest {
  repeated int64 product_ids = 1;
}

// Ответ CORE->ORDER: все поля товара
message Product {
  int64 id = 1;
  string name = 2;
  int64 price = 3;
  int64 amount = 4;
}

message ProductResponse {
  repeated Product products = 1;
}

// Сервис для получения товара из core-сервиса
service ProductService {
  rpc GetProducts (GetProductRequest) returns (ProductResponse);
}