// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0--rc1
// source: order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Забронированный товар
type BookedProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookedProduct) Reset() {
	*x = BookedProduct{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookedProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookedProduct) ProtoMessage() {}

func (x *BookedProduct) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookedProduct.ProtoReflect.Descriptor instead.
func (*BookedProduct) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *BookedProduct) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *BookedProduct) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Запрос списка забронированных товаров
type GetBookedProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookedProductsRequest) Reset() {
	*x = GetBookedProductsRequest{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookedProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookedProductsRequest) ProtoMessage() {}

func (x *GetBookedProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookedProductsRequest.ProtoReflect.Descriptor instead.
func (*GetBookedProductsRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

// Ответ со списком забронированных товаров
type BookedProductsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BookedProducts []*BookedProduct       `protobuf:"bytes,1,rep,name=bookedProducts,proto3" json:"bookedProducts,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BookedProductsResponse) Reset() {
	*x = BookedProductsResponse{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookedProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookedProductsResponse) ProtoMessage() {}

func (x *BookedProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookedProductsResponse.ProtoReflect.Descriptor instead.
func (*BookedProductsResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *BookedProductsResponse) GetBookedProducts() []*BookedProduct {
	if x != nil {
		return x.BookedProducts
	}
	return nil
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\"F\n" +
	"\rBookedProduct\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"\x1a\n" +
	"\x18GetBookedProductsRequest\"V\n" +
	"\x16BookedProductsResponse\x12<\n" +
	"\x0ebookedProducts\x18\x01 \x03(\v2\x14.order.BookedProductR\x0ebookedProducts2c\n" +
	"\fOrderService\x12S\n" +
	"\x11GetBookedProducts\x12\x1f.order.GetBookedProductsRequest\x1a\x1d.order.BookedProductsResponseB\x16Z\x14go-learn/api/grpc/pbb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_order_proto_goTypes = []any{
	(*BookedProduct)(nil),            // 0: order.BookedProduct
	(*GetBookedProductsRequest)(nil), // 1: order.GetBookedProductsRequest
	(*BookedProductsResponse)(nil),   // 2: order.BookedProductsResponse
}
var file_order_proto_depIdxs = []int32{
	0, // 0: order.BookedProductsResponse.bookedProducts:type_name -> order.BookedProduct
	1, // 1: order.OrderService.GetBookedProducts:input_type -> order.GetBookedProductsRequest
	2, // 2: order.OrderService.GetBookedProducts:output_type -> order.BookedProductsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
